# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies without triggering lifecycle scripts if necessary
RUN npm install --ignore-scripts

# Copy all source files
COPY . .

# Build the project
RUN npm run build

# Expose necessary port if needed (not necessary for stdio MCP servers)

# Set entrypoint to Node running the built index.js
ENTRYPOINT ["node", "build/index.js"]
