sr_url=<REPLACE_VALUE_HERE>
sr_cred=<REPLACE_VALUE_HERE>
kafka_api_key=<REPLACE_VALUE_HERE>
kafka_api_secret=<REPLACE_VALUE_HERE>
bootstrap_server=<REPLACE_VALUE_HERE>
region="us-east-2"
aws_profile=<REPLACE_VALUE_HERE>
bucket_name = <REPLACE_VALUE_HERE>
mongo_uri=<REPLACE_VALUE_HERE>
secret_name = "genai_demo_secret_2"<YOU_CAN_EDIT_THIS_IF_YOU_WANT>